// ─── SQUAD DATA — 2026 WORLD CUP ─────────────────────────────────────────────
// Real confirmed squads. Position codes: GK / DF / MF / FW
// Club and caps are approximate at time of squad announcement.

var SQUADS = {

  ENG: {
    manager: 'Thomas Tuchel',
    captain:  'Harry Kane',
    prevBest: 'Winners (1966)',
    worldCups: 8,
    info: 'First WC under Tuchel. Foden & Palmer controversially omitted.',
    squad: [
      { n:'Jordan Pickford',   pos:'GK', club:'Everton',         caps:65  },
      { n:'James Trafford',    pos:'GK', club:'Burnley',         caps:3   },
      { n:'Dean Henderson',    pos:'GK', club:'Crystal Palace',  caps:4   },
      { n:'Reece James',       pos:'DF', club:'Chelsea',         caps:28  },
      { n:'John Stones',       pos:'DF', club:'Man City',        caps:80  },
      { n:'Marc Guehi',        pos:'DF', club:'Crystal Palace',  caps:22  },
      { n:'Ezri Konsa',        pos:'DF', club:'Aston Villa',     caps:14  },
      { n:'Dan Burn',          pos:'DF', club:'Newcastle',       caps:8   },
      { n:'Tino Livramento',   pos:'DF', club:'Newcastle',       caps:5   },
      { n:'Djed Spence',       pos:'DF', club:'Genoa',           caps:3   },
      { n:'Nico O\'Reilly',    pos:'DF', club:'Man City',        caps:2   },
      { n:'Jarell Quansah',    pos:'DF', club:'Liverpool',       caps:4   },
      { n:'Declan Rice',       pos:'MF', club:'Arsenal',         caps:62  },
      { n:'Jude Bellingham',   pos:'MF', club:'Real Madrid',     caps:48  },
      { n:'Jordan Henderson',  pos:'MF', club:'Ajax',            caps:81  },
      { n:'Kobbie Mainoo',     pos:'MF', club:'Man United',      caps:12  },
      { n:'Eberechi Eze',      pos:'MF', club:'Crystal Palace',  caps:18  },
      { n:'Morgan Rogers',     pos:'MF', club:'Aston Villa',     caps:8   },
      { n:'Elliot Anderson',   pos:'MF', club:'Nottm Forest',    caps:4   },
      { n:'Harry Kane',        pos:'FW', club:'Bayern Munich',   caps:102 },
      { n:'Marcus Rashford',   pos:'FW', club:'Aston Villa',     caps:60  },
      { n:'Bukayo Saka',       pos:'FW', club:'Arsenal',         caps:52  },
      { n:'Ollie Watkins',     pos:'FW', club:'Aston Villa',     caps:28  },
      { n:'Anthony Gordon',    pos:'FW', club:'Newcastle',       caps:18  },
      { n:'Noni Madueke',      pos:'FW', club:'Chelsea',         caps:10  },
      { n:'Ivan Toney',        pos:'FW', club:'Al Ahli',         caps:8   },
    ]
  },

  ARG: {
    manager: 'Lionel Scaloni',
    captain:  'Lionel Messi',
    prevBest: 'Winners (1978, 1986, 2022)',
    worldCups: 19,
    info: 'Defending champions. Messi (38) plays his record 6th World Cup.',
    squad: [
      { n:'Emiliano Martínez', pos:'GK', club:'Aston Villa',     caps:52  },
      { n:'Gerónimo Rulli',    pos:'GK', club:'Ajax',            caps:18  },
      { n:'Juan Musso',        pos:'GK', club:'Atalanta',        caps:28  },
      { n:'Nahuel Molina',     pos:'DF', club:'Atlético Madrid', caps:42  },
      { n:'Cristian Romero',   pos:'DF', club:'Tottenham',       caps:38  },
      { n:'Nicolás Otamendi',  pos:'DF', club:'Benfica',         caps:110 },
      { n:'Lisandro Martínez', pos:'DF', club:'Man United',      caps:28  },
      { n:'Nicolás Tagliafico',pos:'DF', club:'Lyon',            caps:62  },
      { n:'Leonardo Balerdi',  pos:'DF', club:'Marseille',       caps:12  },
      { n:'Facundo Medina',    pos:'DF', club:'Lens',            caps:8   },
      { n:'Alexis Mac Allister',pos:'MF',club:'Liverpool',       caps:38  },
      { n:'Rodrigo De Paul',   pos:'MF', club:'Inter Miami',     caps:72  },
      { n:'Enzo Fernández',    pos:'MF', club:'Chelsea',         caps:42  },
      { n:'Leandro Paredes',   pos:'MF', club:'Roma',            caps:62  },
      { n:'Guido Rodríguez',   pos:'MF', club:'Betis',           caps:28  },
      { n:'Nico Paz',          pos:'MF', club:'Como',            caps:8   },
      { n:'Lionel Messi',      pos:'FW', club:'Inter Miami',     caps:188 },
      { n:'Lautaro Martínez',  pos:'FW', club:'Inter Milan',     caps:58  },
      { n:'Julián Álvarez',    pos:'FW', club:'Atlético Madrid', caps:42  },
      { n:'Alejandro Garnacho',pos:'FW', club:'Chelsea',         caps:18  },
      { n:'Nicolás González',  pos:'FW', club:'Atlético Madrid', caps:28  },
      { n:'Giuliano Simeone',  pos:'FW', club:'Atlético Madrid', caps:8   },
      { n:'Thiago Almada',     pos:'FW', club:'Lyon',            caps:12  },
      { n:'Valentín Barco',    pos:'DF', club:'Strasbourg',      caps:6   },
      { n:'José M. López',     pos:'FW', club:'Palmeiras',       caps:4   },
      { n:'Nico Paz',          pos:'MF', club:'Como',            caps:8   },
    ]
  },

  BRA: {
    manager: 'Carlo Ancelotti',
    captain:  'Vinicius Jr',
    prevBest: 'Winners (1958, 62, 70, 94, 2002)',
    worldCups: 23,
    info: 'Neymar retired. Ancelotti\'s first tournament as Brazil boss.',
    squad: [
      { n:'Alisson',           pos:'GK', club:'Liverpool',       caps:78  },
      { n:'Ederson',           pos:'GK', club:'Man City',        caps:38  },
      { n:'Bento',             pos:'GK', club:'Al-Qadsiah',      caps:18  },
      { n:'Danilo',            pos:'DF', club:'Juventus',        caps:68  },
      { n:'Marquinhos',        pos:'DF', club:'PSG',             caps:88  },
      { n:'Gabriel Magalhães', pos:'DF', club:'Arsenal',         caps:28  },
      { n:'Bremer',            pos:'DF', club:'Juventus',        caps:22  },
      { n:'Wendell',           pos:'DF', club:'Porto',           caps:18  },
      { n:'Alex Telles',       pos:'DF', club:'Sevilla',         caps:30  },
      { n:'Lucas Paquetá',     pos:'MF', club:'West Ham',        caps:58  },
      { n:'Bruno Guimarães',   pos:'MF', club:'Newcastle',       caps:38  },
      { n:'Casemiro',          pos:'MF', club:'Man United',      caps:82  },
      { n:'Gerson',            pos:'MF', club:'Marseille',       caps:28  },
      { n:'Andreas Pereira',   pos:'MF', club:'Fulham',          caps:22  },
      { n:'Vinicius Jr',       pos:'FW', club:'Real Madrid',     caps:52  },
      { n:'Rodrygo',           pos:'FW', club:'Real Madrid',     caps:38  },
      { n:'Raphinha',          pos:'FW', club:'Barcelona',       caps:48  },
      { n:'Gabriel Martinelli', pos:'FW',club:'Arsenal',         caps:28  },
      { n:'Endrick',           pos:'FW', club:'Real Madrid',     caps:12  },
      { n:'Savinho',           pos:'FW', club:'Man City',        caps:10  },
    ]
  },

  FRA: {
    manager: 'Didier Deschamps',
    captain:  'Kylian Mbappé',
    prevBest: 'Winners (1998, 2018)',
    worldCups: 16,
    info: 'Two-time winners. Mbappé captain at his third World Cup.',
    squad: [
      { n:'Mike Maignan',      pos:'GK', club:'AC Milan',        caps:28  },
      { n:'Alphonse Areola',   pos:'GK', club:'West Ham',        caps:12  },
      { n:'Kylian Mbappé',     pos:'FW', club:'Real Madrid',     caps:88  },
      { n:'Antoine Griezmann', pos:'FW', club:'Atlético Madrid', caps:138 },
      { n:'Ousmane Dembélé',   pos:'FW', club:'PSG',             caps:62  },
      { n:'Marcus Thuram',     pos:'FW', club:'Inter Milan',     caps:42  },
      { n:'N\'Golo Kanté',     pos:'MF', club:'Al-Ittihad',      caps:62  },
      { n:'Aurélien Tchouaméni',pos:'MF',club:'Real Madrid',     caps:38  },
      { n:'Adrien Rabiot',     pos:'MF', club:'Marseille',       caps:48  },
      { n:'Eduardo Camavinga', pos:'MF', club:'Real Madrid',     caps:28  },
      { n:'Theo Hernández',    pos:'DF', club:'AC Milan',        caps:38  },
      { n:'Jules Koundé',      pos:'DF', club:'Barcelona',       caps:48  },
      { n:'William Saliba',    pos:'DF', club:'Arsenal',         caps:28  },
      { n:'Dayot Upamecano',   pos:'DF', club:'Bayern Munich',   caps:38  },
      { n:'Benjamin Pavard',   pos:'DF', club:'Inter Milan',     caps:58  },
    ]
  },

  GER: {
    manager: 'Julian Nagelsmann',
    captain:  'Joshua Kimmich',
    prevBest: 'Winners (1954, 74, 90, 2014)',
    worldCups: 20,
    info: 'Hosts of Euro 2024 where they lost to Spain in QF.',
    squad: [
      { n:'Manuel Neuer',      pos:'GK', club:'Bayern Munich',   caps:118 },
      { n:'Marc-André ter Stegen',pos:'GK',club:'Barcelona',     caps:42  },
      { n:'Joshua Kimmich',    pos:'MF', club:'Bayern Munich',   caps:88  },
      { n:'Toni Kroos',        pos:'MF', club:'Retired',         caps:106 },
      { n:'Jamal Musiala',     pos:'MF', club:'Bayern Munich',   caps:38  },
      { n:'Florian Wirtz',     pos:'MF', club:'Bayer Leverkusen',caps:28  },
      { n:'Kai Havertz',       pos:'FW', club:'Arsenal',         caps:58  },
      { n:'Leroy Sané',        pos:'FW', club:'Bayern Munich',   caps:62  },
      { n:'Thomas Müller',     pos:'FW', club:'Bayern Munich',   caps:132 },
      { n:'Antonio Rüdiger',   pos:'DF', club:'Real Madrid',     caps:78  },
      { n:'Niklas Süle',       pos:'DF', club:'Dortmund',        caps:52  },
      { n:'David Raum',        pos:'DF', club:'RB Leipzig',      caps:28  },
      { n:'Benjamin Henrichs', pos:'DF', club:'RB Leipzig',      caps:22  },
    ]
  },

  ESP: {
    manager: 'Luis de la Fuente',
    captain:  'Álvaro Morata',
    prevBest: 'Winners (2010)',
    worldCups: 16,
    info: 'Euro 2024 winners. Led by 16-year-old Yamal.',
    squad: [
      { n:'David Raya',        pos:'GK', club:'Arsenal',         caps:18  },
      { n:'Unai Simón',        pos:'GK', club:'Athletic Club',   caps:32  },
      { n:'Lamine Yamal',      pos:'FW', club:'Barcelona',       caps:22  },
      { n:'Nico Williams',     pos:'FW', club:'Athletic Club',   caps:18  },
      { n:'Álvaro Morata',     pos:'FW', club:'AC Milan',        caps:72  },
      { n:'Pedri',             pos:'MF', club:'Barcelona',       caps:42  },
      { n:'Gavi',              pos:'MF', club:'Barcelona',       caps:48  },
      { n:'Rodri',             pos:'MF', club:'Man City',        caps:52  },
      { n:'Fabián Ruiz',       pos:'MF', club:'PSG',             caps:32  },
      { n:'Aymeric Laporte',   pos:'DF', club:'Al Nassr',        caps:38  },
      { n:'Nacho',             pos:'DF', club:'Al Qadsiah',      caps:44  },
      { n:'Dani Carvajal',     pos:'DF', club:'Real Madrid',     caps:62  },
      { n:'Alejandro Balde',   pos:'DF', club:'Barcelona',       caps:18  },
      { n:'Robin Le Normand',  pos:'DF', club:'Atlético Madrid', caps:14  },
    ]
  },

  USA: {
    manager: 'Mauricio Pochettino',
    captain:  'Tyler Adams',
    prevBest: 'QF (2002)',
    worldCups: 12,
    info: 'Co-hosts. Pochettino\'s first major tournament as USA boss.',
    squad: [
      { n:'Matt Turner',       pos:'GK', club:'New England Revolution', caps:38 },
      { n:'Matt Freese',       pos:'GK', club:'NYCFC',          caps:8   },
      { n:'Chris Brady',       pos:'GK', club:'Chicago Fire',   caps:4   },
      { n:'Sergino Dest',      pos:'DF', club:'PSV',            caps:38  },
      { n:'Joe Scally',        pos:'DF', club:'Mönchengladbach',caps:12  },
      { n:'Tim Ream',          pos:'DF', club:'Charlotte FC',   caps:48  },
      { n:'Chris Richards',    pos:'DF', club:'Crystal Palace', caps:22  },
      { n:'Antonee Robinson',  pos:'DF', club:'Fulham',         caps:38  },
      { n:'Mark McKenzie',     pos:'DF', club:'Toulouse',       caps:18  },
      { n:'Miles Robinson',    pos:'DF', club:'FC Cincinnati',  caps:18  },
      { n:'Tyler Adams',       pos:'MF', club:'Bournemouth',    caps:48  },
      { n:'Weston McKennie',   pos:'MF', club:'Juventus',       caps:52  },
      { n:'Gio Reyna',         pos:'MF', club:'Mönchengladbach',caps:28  },
      { n:'Malik Tillman',     pos:'MF', club:'Bayer Leverkusen',caps:18 },
      { n:'Yunus Musah',       pos:'MF', club:'AC Milan',       caps:38  },
      { n:'Brenden Aaronson',  pos:'FW', club:'Leeds United',   caps:38  },
      { n:'Christian Pulisic', pos:'FW', club:'AC Milan',       caps:78  },
      { n:'Timothy Weah',      pos:'FW', club:'Juventus',       caps:38  },
      { n:'Folarin Balogun',   pos:'FW', club:'Monaco',         caps:22  },
      { n:'Josh Sargent',      pos:'FW', club:'Norwich City',   caps:32  },
    ]
  },

  POR: {
    manager: 'Roberto Martínez',
    captain:  'Cristiano Ronaldo',
    prevBest: 'Third place (1966)',
    worldCups: 9,
    info: 'Ronaldo (41) making his record-equalling 6th World Cup.',
    squad: [
      { n:'Diogo Costa',       pos:'GK', club:'Porto',           caps:28  },
      { n:'Rui Patrício',      pos:'GK', club:'Roma',            caps:108 },
      { n:'Cristiano Ronaldo', pos:'FW', club:'Al Nassr',        caps:214 },
      { n:'Bruno Fernandes',   pos:'MF', club:'Man United',      caps:88  },
      { n:'Bernardo Silva',    pos:'MF', club:'Man City',        caps:88  },
      { n:'João Cancelo',      pos:'DF', club:'Barcelona',       caps:58  },
      { n:'Rúben Dias',        pos:'DF', club:'Man City',        caps:68  },
      { n:'Pepe',              pos:'DF', club:'Retired',         caps:142 },
      { n:'Rafael Leão',       pos:'FW', club:'AC Milan',        caps:38  },
      { n:'João Félix',        pos:'FW', club:'Chelsea',         caps:48  },
      { n:'Vitinha',           pos:'MF', club:'PSG',             caps:28  },
      { n:'Nuno Mendes',       pos:'DF', club:'PSG',             caps:32  },
      { n:'Gonçalo Ramos',     pos:'FW', club:'PSG',             caps:18  },
      { n:'Pedro Neto',        pos:'FW', club:'Chelsea',         caps:22  },
    ]
  },

  NED: {
    manager: 'Ronald Koeman',
    captain:  'Virgil van Dijk',
    prevBest: 'Runners-up (1974, 78, 2010)',
    worldCups: 11,
    info: '3× runners-up, never won it. Van Dijk leads experienced squad.',
    squad: [
      { n:'Bart Verbruggen',   pos:'GK', club:'Brighton',        caps:12  },
      { n:'Mark Flekken',      pos:'GK', club:'Brentford',       caps:8   },
      { n:'Virgil van Dijk',   pos:'DF', club:'Liverpool',       caps:78  },
      { n:'Stefan de Vrij',    pos:'DF', club:'Inter Milan',     caps:62  },
      { n:'Matthijs de Ligt',  pos:'DF', club:'Man United',      caps:48  },
      { n:'Denzel Dumfries',   pos:'DF', club:'Inter Milan',     caps:52  },
      { n:'Daley Blind',       pos:'DF', club:'Girona',          caps:98  },
      { n:'Frenkie de Jong',   pos:'MF', club:'Barcelona',       caps:58  },
      { n:'Tijjani Reijnders', pos:'MF', club:'AC Milan',        caps:22  },
      { n:'Teun Koopmeiners',  pos:'MF', club:'Juventus',        caps:28  },
      { n:'Xavi Simons',       pos:'MF', club:'RB Leipzig',      caps:22  },
      { n:'Memphis Depay',     pos:'FW', club:'Corinthians',     caps:98  },
      { n:'Cody Gakpo',        pos:'FW', club:'Liverpool',       caps:38  },
      { n:'Donyell Malen',     pos:'FW', club:'Dortmund',        caps:28  },
      { n:'Wout Weghorst',     pos:'FW', club:'Hoffenheim',      caps:48  },
    ]
  },

  // Lighter data for remaining teams
  MEX: { manager:'Javier Aguirre', captain:'Hirving Lozano', prevBest:'QF (1970, 86)', worldCups:18,
    info:'Co-hosts, playing in front of home fans at Azteca in opener.',
    squad:[
      {n:'Guillermo Ochoa',pos:'GK',club:'AEL Limassol',caps:148},
      {n:'Hirving Lozano',pos:'FW',club:'PSV',caps:88},
      {n:'Raúl Jiménez',pos:'FW',club:'Fulham',caps:102},
      {n:'Edson Álvarez',pos:'MF',club:'Fenerbahce',caps:78},
      {n:'Carlos Acevedo',pos:'GK',club:'Santos Laguna',caps:8},
      {n:'Jorge Sánchez',pos:'DF',club:'PAOK',caps:32},
    ]
  },
  CAN: { manager:'Jesse Marsch', captain:'Alphonso Davies', prevBest:'Group stage (1986)', worldCups:2,
    info:'Co-hosts. Davies leads a golden generation for Canada.',
    squad:[
      {n:'Alphonso Davies',pos:'DF',club:'Bayern Munich',caps:62},
      {n:'Jonathan David',pos:'FW',club:'Lille',caps:48},
      {n:'Milan Borjan',pos:'GK',club:'Red Star Belgrade',caps:62},
      {n:'Cyle Larin',pos:'FW',club:'Club Brugge',caps:72},
      {n:'Tajon Buchanan',pos:'FW',club:'Inter Milan',caps:42},
      {n:'Stephen Eustáquio',pos:'MF',club:'Porto',caps:48},
    ]
  },
  SCO: { manager:'Steve Clarke', captain:'Andy Robertson', prevBest:'Group stage (1974, 78, 82, 90, 98)', worldCups:9,
    info:'First World Cup since 1998. Robertson leads as captain.',
    squad:[
      {n:'Andy Robertson',pos:'DF',club:'Liverpool',caps:72},
      {n:'Scott McTominay',pos:'MF',club:'Napoli',caps:58},
      {n:'Kieran Tierney',pos:'DF',club:'Real Sociedad',caps:52},
      {n:'John McGinn',pos:'MF',club:'Aston Villa',caps:68},
      {n:'Angus Gunn',pos:'GK',club:'Norwich',caps:18},
      {n:'Ryan Christie',pos:'MF',club:'Bournemouth',caps:62},
    ]
  },
  MAR: { manager:'Walid Regragui', captain:'Romain Saïss', prevBest:'SF (2022)', worldCups:7,
    info:'2022 semi-finalists — first African team to reach a WC semi-final.',
    squad:[
      {n:'Yassine Bounou',pos:'GK',club:'Al-Hilal',caps:62},
      {n:'Achraf Hakimi',pos:'DF',club:'PSG',caps:72},
      {n:'Hakim Ziyech',pos:'FW',club:'Galatasaray',caps:62},
      {n:'Sofiane Boufal',pos:'FW',club:'Southampton',caps:48},
      {n:'Youssef En-Nesyri',pos:'FW',club:'Fenerbahce',caps:52},
      {n:'Romain Saïss',pos:'DF',club:'Besiktas',caps:82},
    ]
  },
  JPN: { manager:'Hajime Moriyasu', captain:'Maya Yoshida', prevBest:'R16 (2002, 10, 18, 22)', worldCups:8,
    info:'Knocked out Germany & Spain in Qatar. Dark horses again.',
    squad:[
      {n:'Shuichi Gonda',pos:'GK',club:'Shimizu S-Pulse',caps:42},
      {n:'Takehiro Tomiyasu',pos:'DF',club:'Arsenal',caps:52},
      {n:'Daichi Kamada',pos:'MF',club:'Lazio',caps:38},
      {n:'Ritsu Doan',pos:'MF',club:'Freiburg',caps:48},
      {n:'Takumi Minamino',pos:'FW',club:'Monaco',caps:52},
      {n:'Kaoru Mitoma',pos:'FW',club:'Brighton',caps:38},
    ]
  },
  BEL: { manager:'Domenico Tedesco', captain:'Kevin De Bruyne', prevBest:'Third place (2018)', worldCups:14,
    info:'Golden generation fading — De Bruyne (34) leads one last time.',
    squad:[
      {n:'Koen Casteels',pos:'GK',club:'Wolfsburg',caps:32},
      {n:'Kevin De Bruyne',pos:'MF',club:'Man City',caps:102},
      {n:'Romelu Lukaku',pos:'FW',club:'Napoli',caps:112},
      {n:'Yannick Carrasco',pos:'FW',club:'Al Shabab',caps:68},
      {n:'Toby Alderweireld',pos:'DF',club:'Retired',caps:128},
      {n:'Axel Witsel',pos:'MF',club:'Atlético Madrid',caps:132},
    ]
  },
};
